spring:
  application:
    name: spaceapi
  profiles:
    active: prod

server:
  port: 6970 # 6969 for https proxy

graphql:
  spring-graphql-common:
    clientMutationIdName: clientMutationId
    injectClientMutationId: true
    allowEmptyClientMutationId: false
    mutationInputArgumentName: input
    outputObjectNamePrefix: Payload
    inputObjectNamePrefix: Input
    schemaMutationObjectName: Mutation
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true
    max-query-depth: 3
    exception-handlers-enabled: true

graphiql:
  mapping: /graphiql
  enabled: true
